#Este archivo es para ejecucion en instancia AWS. No usar si se ejecutarán pruebas locales
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
  prebuild:
    commands:
      -npm install
  build:
    commands:
      -npm run test3-nube
  post_build:
    commands:
      - aws s3 sync allure-report s3://reporte-de-pruebas/
      - aws s3 cp --recursive --acl public-read s3://reporte-de-pruebas/ s3://reporte-de-pruebas/ --metadata-directive REPLACE
      - echo "El reporte está disponible en <https://reporte-de-pruebas.s3.us-east-2-amazonaws.com/index.html>"    

